### ISSUE TITLE
Feature Request: Upload old Replays & Select HSReplay server (HSReplay.net or owned)

### ISSUE THREAD

**Issue by Theliel** [HearthSim/HDT-Releases-HSReplay#1]
I'm seeing how the new tracker submit finished games, and should be "easy" to implement as a "sync" or upload manually (folder) old replays, or even those who (by chance of life) connection drops right after winning the game and before the current game will be uploaded. 

At the same time, HSReplay.net work pretty well but will be even better allow to the user add a custom hrreplay server using your HSreplay code

Anyway, good job and thank for your work.

**Comment by jleclanche** [comment]
Hey @Theliel 
Thanks for the feedback. I'm not sure I understand your first suggestion, but if you're talking about uploading old replays/replays that did not upload properly, that is something you can do from HDT already.

Regarding using a custom HSReplay server, that is something we'll consider adding directly in HDT advanced options if people actually deploy other servers, but as that isn't the case right now we are not doing it.
If you intend to run your own HSReplay.net server, let me know and I can help you - the development setup should be simple enough, but the production architecture is actually extremely advanced.

I'm closing this bug tracker (we left it open by mistake) - the email should reach you, but the page will be 404. You can file issues on the following repositories:

- https://github.com/HearthSim/HSReplay.net
- https://github.com/HearthSim/Hearthstone-Deck-Tracker

You can also email us directly at contact@hsreplay.net. Thanks!
